export const COLOR_1 = '#a3cef1';
export const COLOR_2 = '#7bf1a8';
export const COLOR_3 = '#fec89a';
export const COLOR_4 = '#fc7a1e';

const RULE_NOTIFICATION_REGISTER_SCHEDULE =
  'RULE_NOTIFICATION_REGISTER_SCHEDULE';
const RULE_NOTIFICATION_CANCEL_SCHEDULE = 'RULE_NOTIFICATION_CANCEL_SCHEDULE';
const RULE__SCHEDULE = 'SCHEDULE';
const RULE_DOCTOR_REMIND = 'RULE_DOCTOR_REMIND'; // bác sĩ nhắc nhở
const RULE_SYSTEM = 'RULE_SYSTEM';
const RULE_INFORMATION = 'RULE_INFORMATION';
const RULE_ALL = 'RULE_ALL';
const RULE_HAS_SEEN = 'RULE_HAS_SEEN';

export const type = {
  RULE_DOCTOR_REMIND,
  RULE_INFORMATION,
  RULE_NOTIFICATION_CANCEL_SCHEDULE,
  RULE_NOTIFICATION_REGISTER_SCHEDULE,
  RULE_SYSTEM,
  RULE_ALL,
  RULE__SCHEDULE,
  RULE_HAS_SEEN,
};
