const RouterKey = {
  LOGIN_SCREEN: 'LoginScreen',
  REGISTER_SCREEN: 'RegisterScreen',
  SEND_IN4_SCREEN: 'SendInformationScreen',
  MAIN_SCREEN: 'MainScreen',
  HOME_SCREEN: 'HomeScreen',
  MESSAGE_SCREEN: 'MessageScreen',
  AUTH_PHONE_SCREEN: 'AuthPhoneScreen',
  ROUTER_INFO_SCREEN: 'RouterInfoScreen',
  INFO_SCREEN: 'InfoScreen',
  INFO_BMI_SCREEN: 'BMIScreen',
  SCHEDULE_ROUTER_SCREEN: 'ScheduleRouterScreen',
  SCHEDULE_LIST_SCREEN: 'ScheduleListScreen',
  SCHEDULE_DETAIL_SCREEN: 'ScheduleDetailScreen',
  SCHEDULE_DETAIL_REGISTER_SCREEN: 'ScheduleDetailRegisterScreen',
  CONVERSATION_SCREEN: 'ConversationScreen',
  CONVERSATION_DETAIL_SCREEN: 'ConversationDetailScreen',
  LOADING_SCREEN: 'LoadingScreen',
  CALL_VIDEO_SCREEN: 'CallVideoScreen',
  GLYCEMIC_SCREEN: 'GlycemicScreen',
  NOTIFICATION_SCREEN: 'NotificationScreen',
  BLOOD_SCREEN: 'BloodScreen',
};

export default RouterKey;
