const RouterKey = {
  LOGIN_SCREEN: 'LoginScreen',
  REGISTER_SCREEN: 'RegisterScreen',
  SEND_IN4_SCREEN: 'SendInformationScreen',
  MAIN_SCREEN: 'MainScreen',
  HOME_SCREEN: 'HomeScreen',
  MESSAGE_SCREEN: 'MessageScreen',
  AUTH_PHONE_SCREEN: 'AuthPhoneScreen',
  ROUTER_INFO_SCREEN: 'RouterInfoScreen',
  INFO_SCREEN: 'InfoScreen',
  INFO_BMI_SCREEN: 'BMIScreen',
  SCHEDULE_ROUTER_SCREEN: 'ScheduleRouterScreen',
  SCHEDULE_LIST_SCREEN: 'ScheduleListScreen',
  SCHEDULE_DETAIL_SCREEN: 'ScheduleDetailScreen',
  SCHEDULE_DETAIL_REGISTER_SCREEN: 'ScheduleDetailRegisterScreen',
  CONVERSATION_SCREEN: 'ConversationScreen',
  CONVERSATION_DETAIL_SCREEN: 'ConversationDetailScreen',
  LOADING_SCREEN: 'LoadingScreen',
  LOADING_AFTER_LOGIN_SCREEN: 'LoadingAfterLoginScreen',
  CALL_VIDEO_SCREEN: 'CallVideoScreen',
  GLYCEMIC_SCREEN: 'GlycemicScreen',
  NOTIFICATION_SCREEN: 'NotificationScreen',
  BLOOD_SCREEN: 'BloodScreen',
  PROFILE_PATIENT_SCREEN: 'ProfilePatientScreen',
  DOCTOR_SCREEN: 'DoctorScreen',
  DOCTOR_HOME_SCREEN: 'DoctorHomeScreen',
  DOCTOR_HOME_LIST_EXAM_SCREEN: 'DoctorHomeListExamScreen',
  DOCTOR_HOME_PATIENT_INFO_SCREEN: 'DoctorPatientInfoScreen',
  DOCTOR_CONVERSATION_SCREEN: 'DoctorConversationScreen',
  DOCTOR_CONVERSATION_LIST_SCREEN: 'DoctorConversationListScreen',
  DOCTOR_CONVERSATION_DETAIL_SCREEN: 'DoctorConversationDetail',
  DOCTOR_NOTIFICATION_SCREEN: 'DoctorNotificatonScreen',
  DOCTOR_INFO_SCREEN: 'DoctorInfoScreen',
  UTILS_CHAT_GPT_SCREEN: 'ChatGPTScreen',
  UTILS_POST_LIST_SCREEN: 'PostListScreen',
  UTILS_POST_DETAIL_SCREEN: 'PostDetailScreen',
};

export default RouterKey;
